version: "3.9"
services:
  agent-test-dev:
    container_name: agent-test-dev
    build:
      context: ../
      dockerfile: Dockerfile
      target: dev
    tty: true
    env_file:
      - ../agent-test.env
    volumes:
      - ../:/workspace
